# Use the official Postgres image as a base
FROM postgres:15

# Install PostGIS and dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgis postgresql-15-postgis-3 && \
    rm -rf /var/lib/apt/lists/*

# Set up Postgres extensions
# This ensures PostGIS extensions are installed in the database at runtime
COPY setup-postgis.sh /docker-entrypoint-initdb.d/setup-postgis.sh

# Expose the default Postgres port
EXPOSE 5432