services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_prod
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DEBUG: "False"
      ALLOWED_HOSTS: "render.com"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
    # No volume mount needed for code in production

  db:
    image: postgres:13
    container_name: django_db
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    volumes:
      postgres_data:
        driver: local
        driver_opts:
          type: none
          o: bind
          device: /Users/onur/Dev/serial_experiments/python/PharmacyOnDuty/postgres_data
