FROM python:3.13-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Install dependencies
RUN pip install --upgrade pip && pip install -r requirements.txt

# Install system dependencies for geospatial libraries
RUN apt-get update && apt-get install -y \
    binutils libproj-dev gdal-bin \
    && apt-get clean

CMD ["celery", "-A", "PharmacyOnDuty", "worker", "-l", "info"]
