version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: dockerfile.prod
    ports:
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DJANGO_DEBUG=False
    command: >
      sh -c "mkdir -p /app/staticfiles &&
             python manage.py collectstatic --noinput &&
             gunicorn PharmacyOnDuty.wsgi:application --bind 0.0.0.0:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    depends_on:
      - django
    ports:
      - "80:80" # Only HTTP for now
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgis-data:
