version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    ports:
      - "5678:5678" # optional
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DJANGO_DEBUG=False
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    command: >
      sh -c "mkdir -p /app/staticfiles &&
             python manage.py collectstatic --noinput &&
             gunicorn PharmacyOnDuty.wsgi:application --bind 0.0.0.0:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    restart: always
    depends_on:
      - django
    ports:
      - "127.0.0.1:8081:80"
      - "127.0.0.1:8444:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD}

  beat:
    build: .
    restart: always
    command: celery -A PharmacyOnDuty beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgis-data:
  redis_data:
