services:

  django:
    build: .
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - REMOTE_DEBUGGING_PORT=5678
      - ALLOWED_HOSTS=pharmacyonduty.onrender.com

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data:
