version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_dev
    depends_on:
      - db
    ports:
      - "8000:8000"  # Django dev server
      - "5678:5678"  # Debugger port
    networks:
      - default
    volumes:
      - .:/app       # Mount code for hot-reload
    environment:
      DEBUG: "True"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME: "gis"
      DB_USER: "postgres"
      DB_PASSWORD: "password"
      DB_HOST: "db"
      DB_PORT: "5432"