version: '3.8'

services:
  django:
    build: .
    expose:
      - "8000"
    ports:
      - "5678:5678" # For remote debugging (optional)
      - "8000:8000" # For HTTP access (accessible from outside, useful for admin panel)
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - REMOTE_DEBUGGING_PORT=5678 # Optional
    restart: unless-stopped

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./remotedev_nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl/certs:ro
      - ./private:/etc/ssl/private:ro
    depends_on:
      - django
    restart: unless-stopped

volumes:
  postgis-data:


