version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: dockerfile.prod
    restart: always
    ports:
      - "5678:5678" # optional
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DJANGO_DEBUG=False
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: >
      sh -c "mkdir -p /app/staticfiles &&
             python manage.py collectstatic --noinput &&
             gunicorn PharmacyOnDuty.wsgi:application --bind 0.0.0.0:8000"

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgis
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: gis
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    container_name: django_nginx
    restart: always
    depends_on:
      - django
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot_webroot:/var/www/certbot
      - ./certbot_letsencrypt:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    restart: always
    # Temporarily remove the entrypoint so we can do the initial issuance
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot_webroot:/var/www/certbot
      - ./certbot_letsencrypt:/etc/letsencrypt

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    restart: always
    command: celery -A PharmacyOnDuty worker -l info --hostname=scraper@%%h
    environment:
      - DJANGO_SETTINGS_MODULE=PharmacyOnDuty.settings
    volumes:
      - .:/app

  beat:
    build: .
    restart: always
    command: celery -A PharmacyOnDuty beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    depends_on:
      - redis
      - db
    volumes:
      - .:/app

volumes:
  postgis-data:
  redis_data:
