# Generated by Django 5.1.4 on 2025-01-06 19:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        default="POINT(0 0)", srid=4326
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("district", models.CharField(max_length=100)),
                ("phone", models.CharField(blank=True, max_length=10, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("duty_start", models.TimeField(blank=True, null=True)),
                ("duty_end", models.TimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pharmacies",
                        to="pharmacies.city",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkingSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday_start", models.TimeField()),
                ("weekday_end", models.TimeField()),
                ("saturday_start", models.TimeField()),
                ("saturday_end", models.TimeField()),
                (
                    "city",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_schedule",
                        to="pharmacies.city",
                    ),
                ),
            ],
        ),
    ]
