# Generated by Django 5.1.4 on 2025-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="phone",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
