# Generated by Django 5.1.4 on 2025-01-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0002_alter_pharmacy_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="address",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
