# Generated by Django 5.1.4 on 2025-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacies", "0004_alter_pharmacy_duty_end_alter_pharmacy_duty_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="last_scraped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
