# Generated by Django 5.1.4 on 2025-02-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0006_alter_city_options_alter_pharmacy_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pharmacies.city')),
                ('interval', models.PositiveIntegerField(default=24, help_text='Update interval in hours')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
